[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ["-Clink-arg=-Tsrc/link.ld"]

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -m 128M -smp 1 -nographic -kernel "	
