[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ["-Clink-arg=-Tsrc/virt.ld"]

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -bios none -m 128M -smp 4 -nographic -kernel "	
